AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 25
INCLUDE_TOP: False
<<<<<<< HEAD
EPOCHS: 10
=======
EPOCHS: 1
>>>>>>> e6a3ba686f228a3a40e183aef0d9a6b6b5371220
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.02
